config/routes.rb
Rails.application.routes.draw do
  root 'bookmarks#index'

  resources :kinds
  resources :categories
  resources :bookmarks
  get 'categories/:id/api', to: 'categories#api', as: 'api'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
    belongs_to :kind
    belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :parent, class_name: 'Category', optional: true, foreign_key: :category_id
    has_many :children, class_name: 'Category', dependent: :destroy 
    has_many :bookmarks
end

app/models/kind.rb
class Kind < ApplicationRecord
    has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: %i[ show edit update destroy ]

  # GET /bookmarks or /bookmarks.json
  def index
    @bookmarks = Bookmark.all
    @bookmark = Bookmark.new
    @bookmarks_cat = Bookmark.joins(:category).group("categories.name").count
    @chartz = Bookmark.joins(:kind).group("kinds.name").count
  end

  # GET /bookmarks/1 or /bookmarks/1.json
  def show
    respond_to do |format|
      format.js 
      format.html { render :show }
    end
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks or /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: "Bookmark was successfully created." }
        format.json { render :show, status: :created, location: @bookmark }
        format.js
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1 or /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: "Bookmark was successfully updated." }
        format.json { render :show, status: :ok, location: @bookmark }
        format.js 
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1 or /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url, notice: "Bookmark was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookmark
      @bookmark = Bookmark.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bookmark_params
      params.require(:bookmark).permit(:title, :url, :category_id, :kind_id)
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  def api
    category = Category.find(params[:id])
    hash = {
      name: category.name,
      private: category.private,
      category_id: category.category_id,
      bookmarks: category.bookmarks.pluck(:title)
    }
    render json: hash
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :private, :category_id)
    end
end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController
  before_action :set_kind, only: %i[ show edit update destroy ]

  # GET /kinds or /kinds.json
  def index
    @kinds = Kind.all
  end

  # GET /kinds/1 or /kinds/1.json
  def show
  end

  # GET /kinds/new
  def new
    @kind = Kind.new
  end

  # GET /kinds/1/edit
  def edit
  end

  # POST /kinds or /kinds.json
  def create
    @kind = Kind.new(kind_params)

    respond_to do |format|
      if @kind.save
        format.html { redirect_to @kind, notice: "Kind was successfully created." }
        format.json { render :show, status: :created, location: @kind }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kinds/1 or /kinds/1.json
  def update
    respond_to do |format|
      if @kind.update(kind_params)
        format.html { redirect_to @kind, notice: "Kind was successfully updated." }
        format.json { render :show, status: :ok, location: @kind }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kinds/1 or /kinds/1.json
  def destroy
    @kind.destroy
    respond_to do |format|
      format.html { redirect_to kinds_url, notice: "Kind was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kind
      @kind = Kind.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def kind_params
      params.require(:kind).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/graphics_helper.rb
module GraphicsHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/views/bookmarks/_bookmark-detail.html.erb
<td><%= bookmark.title %></td>
<td><%= bookmark.url %></td>
<td><%= bookmark.category.name %></td>
<td><%= bookmark.kind.name %></td>

<td><%= link_to 'Show', bookmark, class: 'btn btn-warning rounded-pill' %></td>
<td><%= link_to 'Edit', edit_bookmark_path(bookmark), class: 'btn btn-warning rounded-pill' %></td>
<td><%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning rounded-pill' %></td>

app/views/bookmarks/_bookmark.html.erb
<tr id="bookmark-<%= bookmark.id %>">
  <%= render 'bookmark-detail', bookmark: bookmark %>
</tr> 

app/views/bookmarks/_form.html.erb
<%= form_with(model: bookmark,data: {confirm: 'Save Bookmark?'}, local: false) do |form| %>
  <% if bookmark.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bookmark.errors.count, "error") %> prohibited this bookmark from being saved:</h2>

      <ul>
        <% bookmark.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class= "container">
<h1>Create a BookMark</h1>
  <div class="form-row">
      <div class="form-group col-md-4">
        <%= form.text_field :title, autofocus: true, autocomplete: "Name", class:'form-control', placeholder: 'Title' %>
      </div>

      <div class="form-group col-md-4">
        <%= form.text_field :url, autofocus: true, autocomplete: "URL", class:'form-control', placeholder: 'URL' %>
      </div>
  </div>

  <div class="form-row">
      <div class="form-group col-md-4">
        <h5><%= form.label "Select Kinds" %></h5> 
        <%= form.select :kind_id, Kind.all.collect {|k| [k.name, k.id]}, {} ,id: :bookmark_kind_id, include_blank:false %>

      </div>
      
      <div class="form-group col-md-4">
        <h5><%= form.label "Select Categories" %></h5>  
        <%= form.select :category_id, Category.all.collect {|c| [c.name, c.id]}, {} ,id: :bookmark_category_id, include_blank:false %>
      </div>
  </div>

      <div class="actions">
        <%= form.submit class: 'btn btn-warning rounded-pill' %>
      </div>

</div>

<% end %>

app/views/bookmarks/create.js.erb
$('#table_bookmarks').append(`
    <tr>
        <td><%= @bookmark.title %></td>
        <td><%= @bookmark.url %></td>
        <td><%= @bookmark.kind.name %></td>
        <td><%= @bookmark.category.name %></td>
        <td><%= link_to 'Show', @bookmark %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(@bookmark) %></td>
        <td><%= link_to 'Destroy', @bookmark, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
                            `)

app/views/bookmarks/edit.html.erb
<h1>Editing Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Big Bang Marks</h1>
    <p class="lead">These are some BookMarks showing the discography of Big Bang, including DVDs and solo material!</p>
  </div>
</div>


<div class="container">
<div class="m-4">
  <%= render 'form', bookmark: @bookmark %>
</div>

<table class="table table-hover" id="table_bookmarks">
<h1>Current BookMarks</h1>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Category</th>
      <th>Kind</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
     <tr>
      <%= render @bookmarks %>
     </tr>
  </tbody>
</table>

<br>

  <h1 class="text-center">Graphics</h1>
  <div class="row">
    <div class="col">
      <h3>Categories</h3>
      <%= pie_chart @bookmarks_cat %>
    </div>

    <div class="col">
    <h3>Kind</h3>
    <%= pie_chart @chartz %>
    </div>
  </div>

</div>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render 'form', bookmark: @bookmark %>

<%= link_to 'Back', bookmarks_path, class: 'btn btn-buttom rounded-pill' %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">

<div class="card my-3" style="width: 18rem;">
  <div class="card-header">
    <strong>Title:</strong>
    <%= @bookmark.title %>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
    <strong>Kind:</strong>
    <%= @bookmark.kind.name %>
    </li>
    <li class="list-group-item">
    <strong>Url:</strong>
    <%= @bookmark.url %>
    </li>
    <li class="list-group-item">
    <strong>Category:</strong>
    <%= @bookmark.category.name %>
    </li>
  </ul>
</div>

<%= link_to 'Edit', edit_bookmark_path(@bookmark), class: 'btn btn-warning rounded-pill' %> |
<%= link_to 'Back', bookmarks_path, class: 'btn btn-warning rounded-pill' %>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :private %>
    <%= form.check_box :private %>
  </div>

  <div class="field">
    <%= form.label :categories_id %>
    <%= form.text_field :categories_id %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-warning rounded-pill' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category, class: 'btn btn-warning rounded-pill' %> |
<%= link_to 'Back', categories_path, class: 'btn btn-warning rounded-pill' %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Categories</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Private</th>
      <th>Categories</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.private %></td>
        <td><%= category.category_id %></td>
        <td><%= link_to 'Show', category, class: 'btn btn-warning rounded-pill' %></td>
        <td><%= link_to 'Edit', edit_category_path(category), class: 'btn btn-warning rounded-pill' %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning rounded-pill' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path, class: 'btn btn-warning rounded-pill' %>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Private:</strong>
  <%= @category.private %>
</p>

<p>
  <strong>ID:</strong>
  <%= @category.id %>
</p>

<%= link_to 'More Info', api_path(@category), class: 'btn btn-warning rounded-pill' %> |
<%= link_to 'Edit', edit_category_path(@category), class: 'btn btn-warning rounded-pill' %> |
<%= link_to 'Back', categories_path, class: 'btn btn-warning rounded-pill' %>
</div>

app/views/kinds/_form.html.erb
<%= form_with(model: kind, local: true) do |form| %>
  <% if kind.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kind.errors.count, "error") %> prohibited this kind from being saved:</h2>

      <ul>
        <% kind.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/kinds/edit.html.erb
<h1>Editing Kind</h1>

<%= render 'form', kind: @kind %>

<%= link_to 'Show', @kind %> |
<%= link_to 'Back', kinds_path %>

app/views/kinds/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Kinds</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kinds.each do |kind| %>
      <tr>
        <td><%= kind.name %></td>
        <td><%= link_to 'Show', kind, class: 'btn btn-warning rounded-pill' %></td>
        <td><%= link_to 'Edit', edit_kind_path(kind), class: 'btn btn-warning rounded-pill' %></td>
        <td><%= link_to 'Destroy', kind, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning rounded-pill' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kind', new_kind_path, class: 'btn btn-warning rounded-pill' %>
</div>

app/views/kinds/new.html.erb
<h1>New Kind</h1>

<%= render 'form', kind: @kind %>

<%= link_to 'Back', kinds_path, class: 'btn btn-warning rounded-pill' %>

app/views/kinds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kind.name %>
</p>

<%= link_to 'Edit', edit_kind_path(@kind) %> |
<%= link_to 'Back', kinds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookMarks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-warning">
  <%= link_to 'Big Bang Marks', bookmarks_path , class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to 'Category', categories_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
          <%= link_to 'Kind', kinds_path, class:"nav-link" %>
      </li>
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>